kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: dynamic-config
data:
  .dockerconfigjson: <base 64 config json here>