version: '3'
networks: 
  public:
  internal:
services:
  dynamic-config-redis-storage:
    image: redis
    container_name: dynamic-config-redis-storage
    networks: 
      - internal
  dynamic-config-database-primer:
    build: 
      context: .
      dockerfile: src/clients/DatabasePrimer.Service/Dockerfile
    depends_on: 
      - dynamic-config-redis-storage
    networks: 
      - internal
  dynamic-config-storage-api:
    build: 
      context: .
      dockerfile: src/DynamicConfig.Storage.Api/Dockerfile
    image: dynamic-config-storage-api
    container_name: dynamic-config-storage-api
    depends_on: 
      - dynamic-config-redis-storage
    networks: 
      - internal
      - public
  client-service-a:
    build:
      context: .
      dockerfile: src/clients/WorkerService.ServiceA/Dockerfile
    image: client-service-a
    container_name: client-service-a
    networks: 
      - public